=head1 NAME

MyTest::Foo1 -

=head1 SYNOPSIS

  use MyTest::Foo1;

=head1 DESCRIPTION

MyTest::Foo1 is

=head1 AUTHOR

Default Name E<lt>yappo <at> shibuya <döt> plE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

